# Build settings
source: ./docs
destination: ./_site

# Serving
detach: false
port: 4000
host: 127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

kramdown:
  syntax_highlighter_opts:
    css_class: "highlight"

sass:
  sass_dir: assets/css
  style: :expanded # :compressed

# safe: true
# whitelist: []
plugins: []
#   - jekyll-sitemap
#   - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Outputting
# permalink: /:title/

# Variables
url: "https://www.highridge-hr.co.uk"
title: Highridge HR Consultancy

name: Highridge HR Consultancy
email: contact@highridge-hr.co.uk
description: >-
  Specialising in Insurance and Financial Services SME businesses, 
  Highridge HR works as your HR team to ensure your focus is on people, 
  not process.

social:
  linkedin: highridge-hr
  twitter: highridge-hr
  # github: highridge-hr

google_analytics:
