- title: Performance management
  icon: services-performance
  desc:

- title: Disciplinaries
  icon: services-disciplinary
  desc:

- title: Grievances
  icon: services-grievances
  desc:

- title: Sickness and absence
  icon: services-sickness
  desc:

- title: Redundancy
  icon: services-redundancy
  desc:

- title: TUPE
  icon: services-tupe
  desc:

- title: Acquisition (HR due diligence)
  icon: services-acquisition
  desc:

- title: Succession planning
  icon: services-succession-planning
  desc:

- title: Employee mental health
  icon: services-mental-health
  desc:

- title: Training and development
  icon: services-training
  desc:
